Added the kns formula.
blendle/homebrew-blendle pull request #1
Opened 2017-04-27 11:18 UTC by koenbollen

So people can install https://gist.github.com/koenbollen/342c138b6a77d3de6869aad68c193617

2017-05-01 11:11 UTC, koenbollen commented
@koenrh @JeanMertz 👍❓

2017-05-02 12:01 UTC, arnov approved these changes
afaik

2017-05-02 12:20 UTC, jewilmeer approved these changes
lgtm 🎉

2017-05-02 12:44 UTC, koenbollen commented
I'm going to wait for an approval by @koenrh. He should be back tomorrow.

2017-05-03 16:46 UTC, JeanMertz requested changes
Awesome to contribute this 👍 

I'm requesting a change, but in general, I'm extremely happy to see this take off and have more tools easily available to all developers 🎉 

As we talked about over Slack: I'd like to see the script be available somewhere under our GH organisation, so we can change it if we ever need to.

2017-05-04 12:57 UTC, koenrh commented on Formula/kns.rb
> +    prefix.install 'kns.bash'
I think Homebrew Core now supports installing completions:

Not tested, but I think you could add this to the `install` method, and then remove `post_install`:

```
bash_completion.install "kns.bash"
zsh_completion.install "kns.bash"
```

2017-05-04 12:58 UTC, koenrh commented
@JeanMertz That would be nice. We could simply add a separate repository for all shell-completions. Like I did here for shell-scripts: https://github.com/koenrh/shell-scripts (https://github.com/koenrh/homebrew-scripts).

2017-05-05 08:59 UTC, koenbollen commented
@koenrh They are not completions. 😄 Just a function to call.

@JeanMertz I'll create a clone of my gist in a blendle repo soon.

2017-05-05 14:42 UTC, koenrh approved these changes

2017-05-05 14:42 UTC, koenrh commented on Formula/kns.rb
> +    I really recommend this alias:
![image](https://cloud.githubusercontent.com/assets/1307291/25750367/c6172784-31b1-11e7-95be-4dadbbe69c01.png)

2017-05-05 14:43 UTC, koenbollen commented on Formula/kns.rb
> +    I really recommend this alias:
I do, really. Recommend that alias!

2017-05-05 14:45 UTC, JeanMertz approved these changes
awesome

2017-05-05 14:54 UTC, merged

2017-05-05 15:23 UTC, JeanMertz commented
@koenbollen one thing I noticed:

I installed `kubectl` using `gcloud component install kubectl`, and that's what we advice people to do in tons of `script/bootstrap` scripts as well, because that way, you get notified if an update is available.

This formula _depends_ on `kubernetes-cli`, meaning Homebrew overwrote my kubectl.

Would be nice if this was a soft-dependency, so that doesn't happen to everyone.

2017-05-08 09:28 UTC, koenbollen commented
@JeanMertz Agreed, will fix. :+1:

2017-05-08 09:59 UTC, koenrh commented
@koenbollen It doesn't necessarily need to be a 'completion'. See: https://github.com/ahmetb/kubectx